import React, { memo, useEffect, useRef } from 'react'
import {
  TouchableOpacity,
  View,
  Text,
  StyleSheet,
  Dimensions,
  Animated,
} from 'react-native'
import type { StyleProp, ViewStyle, TextStyle } from 'react-native'
import type { DateItem } from '../utils/types'
import type { Theme } from '../theme/types'
import type {
  DayCellState,
  GetDayColor,
  GetDayStyle,
  GetDayTextStyle,
  GetDayContent,
} from './types'

type Props = {
  day: DateItem
  onPress: (day: DateItem) => void
  startDate: Date | null
  endDate: Date | null
  theme: Theme
  /** Whether this day is strictly between startDate and endDate (range mode). */
  isInRange?: boolean
  /** Minimum selectable date — dates before this are disabled. */
  minDate?: Date
  /** Maximum selectable date — dates after this are disabled. */
  maxDate?: Date
  /** Disable range band animation (band appears instantly). */
  disableAnimation?: boolean
  /** Custom day cell renderer — full override for the touchable children. */
  renderDay?: (day: DateItem, state: DayCellState) => React.ReactNode
  /** Style applied to the outer touchable slot. */
  style?: StyleProp<ViewStyle>
  /** Style applied on top of the selected circle. */
  selectedStyle?: StyleProp<ViewStyle>
  /** Style applied on top of the range band fill. */
  rangeStyle?: StyleProp<ViewStyle>
  /** Style applied on top of the day number text. */
  textStyle?: StyleProp<TextStyle>
  /** Per-day text color override. Return `undefined` to use the default. */
  getDayColor?: GetDayColor
  /** Per-day slot style override. Composed on top of `style`. */
  getDayStyle?: GetDayStyle
  /** Per-day text style override. Composed on top of `textStyle`. */
  getDayTextStyle?: GetDayTextStyle
  /** Per-day custom content. Replaces the default day-number <Text>. */
  getDayContent?: GetDayContent
}

// Re-export for backward compatibility (originally declared here).
export type { DayCellState } from './types'

const toDate = (date: Date | string | null) => {
  if (!date) return null
  const parsed = typeof date === 'string' ? new Date(date) : date
  if (isNaN(parsed.getTime())) return null
  const d = new Date(parsed.getTime())
  d.setHours(0, 0, 0, 0)
  return d
}

const isSameDate = (a: Date | null, b: Date | null) => {
  if (!a || !b) return false
  return (
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate()
  )
}

const { width: screenWidth } = Dimensions.get('window')

// One grid cell owns a full slot of the 7-column row. Background bands fill
// the slot edge-to-edge, so adjacent in-range cells visually connect without
// leaking into neighbouring slots (which would clip neighbouring text).
const SLOT = Math.floor((screenWidth - 32) / 7)
const CIRCLE = Math.min(SLOT - 8, 44)

const DayCell: React.FC<Props> = ({
  day,
  onPress,
  startDate,
  endDate,
  theme,
  isInRange = false,
  minDate,
  maxDate,
  disableAnimation = false,
  renderDay,
  style,
  selectedStyle,
  rangeStyle,
  textStyle,
  getDayColor,
  getDayStyle,
  getDayTextStyle,
  getDayContent,
}) => {
  const startDateNorm = toDate(startDate)
  const endDateNorm = toDate(endDate)
  const dayDate = toDate(day.fullDate)

  const isRangeStart = isSameDate(startDateNorm, dayDate)
  const isRangeEnd = isSameDate(endDateNorm, dayDate)
  const isSelected = isRangeStart || isRangeEnd
  // A valid range exists only when both endpoints are set and distinct.
  const hasValidRange =
    !!startDateNorm &&
    !!endDateNorm &&
    !isSameDate(startDateNorm, endDateNorm)

  let isDisabled = !dayDate
  if (dayDate) {
    if (minDate) {
      const min = toDate(minDate)
      if (min && dayDate < min) isDisabled = true
    }
    if (maxDate) {
      const max = toDate(maxDate)
      if (max && dayDate > max) isDisabled = true
    }
  }

  // Some DateItems generated by older callers may not carry isSaturday; infer.
  const isSaturday =
    typeof day.isSaturday === 'boolean'
      ? day.isSaturday
      : (() => {
          const d = toDate(day.fullDate)
          return d ? d.getDay() === 6 : false
        })()

  const state: DayCellState = {
    isSelected,
    isInRange,
    isDisabled,
    isToday: day.isToday,
    isHoliday: day.isHoliday,
    isSunday: day.isSunday,
    isSaturday,
  }

  if (day.isEmpty) {
    return <View style={[styles.slot, style]} />
  }

  if (renderDay) {
    return (
      <TouchableOpacity
        activeOpacity={0.9}
        onPress={() => !isDisabled && onPress(day)}
        disabled={isDisabled}
        style={[styles.slot, style]}>
        {renderDay(day, state)}
      </TouchableOpacity>
    )
  }

  // Decide which part of the range band to render in this cell:
  // - Middle day in range: full-width band
  // - Range start with valid range: right half only (connects to next cell)
  // - Range end with valid range: left half only (connects to prev cell)
  let bandStyle: any = null
  if (isInRange) {
    bandStyle = styles.bandFull
  } else if (hasValidRange && isRangeStart) {
    bandStyle = styles.bandRight
  } else if (hasValidRange && isRangeEnd) {
    bandStyle = styles.bandLeft
  }

  // Progress bar fill: band grows from left to right (scaleX 0 → 1 with a
  // left-anchored origin). Delay each day from startDate so the range fills
  // cell-by-cell left-to-right instead of every cell animating in place.
  //
  // RN's default scale origin is center, so we pair scaleX with a translateX
  // of `-((1 - progress) * width / 2)` to keep the left edge pinned while it
  // expands to the right. Both transforms run on the native driver.
  const bandWidth = bandStyle === styles.bandFull ? SLOT : SLOT / 2
  const progress = useRef(new Animated.Value(disableAnimation ? 1 : 0)).current
  useEffect(() => {
    if (!bandStyle) {
      progress.setValue(0)
      return
    }
    if (disableAnimation) {
      progress.setValue(1)
      return
    }
    const MS_PER_DAY = 1000 * 60 * 60 * 24
    let diffDays = 0
    if (startDateNorm && dayDate) {
      diffDays = Math.max(
        0,
        Math.round((dayDate.getTime() - startDateNorm.getTime()) / MS_PER_DAY),
      )
    }
    // Per-cell fill duration roughly matches one stagger step so consecutive
    // cells' animations overlap just enough to look continuous.
    const PER_CELL_MS = 70
    const CELL_DURATION = 120
    const delay = Math.min(diffDays * PER_CELL_MS, 800)
    progress.setValue(0)
    Animated.timing(progress, {
      toValue: 1,
      duration: CELL_DURATION,
      delay,
      useNativeDriver: true,
    }).start()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [bandStyle, startDateNorm?.getTime(), endDateNorm?.getTime(), disableAnimation])

  // Keep the left edge fixed while scaleX animates: shift by half the "empty"
  // portion of the unscaled width.
  const bandTranslateX = Animated.multiply(
    Animated.subtract(1, progress),
    -bandWidth / 2,
  )

  // Weekend color resolution: weekendColor wins over saturday/sunday colors.
  const weekendOverride = theme.weekendColor
  const satColor = weekendOverride ?? theme.saturdayColor
  const sunColor = weekendOverride ?? theme.sundayColor

  // Per-day color callback wins over the default chain. Returning `undefined`
  // means "fall through to the default resolution".
  const overrideColor = getDayColor ? getDayColor({ day, state, theme }) : undefined

  const textColor =
    overrideColor ??
    (isSelected
      ? theme.selectedTextColor
      : isDisabled
        ? theme.disabledColor
        : day.isSunday
          ? sunColor
          : isSaturday && satColor
            ? satColor
            : day.isHoliday
              ? theme.holidayColor
              : theme.textColor)

  const fontSize = theme.fontSize?.day ?? 14

  // Per-day slot / text style overrides are composed ON TOP of user-provided
  // style props so they can selectively patch individual cells.
  const overrideSlotStyle = getDayStyle ? getDayStyle({ day, state, theme }) : undefined
  const overrideTextStyle = getDayTextStyle
    ? getDayTextStyle({ day, state, theme })
    : undefined

  // Custom per-day content replaces the default <Text>{day.day}</Text>. If the
  // callback returns `undefined` we fall back to the default number text.
  const customContent = getDayContent
    ? getDayContent({ day, state, theme })
    : undefined

  return (
    <TouchableOpacity
      activeOpacity={0.9}
      onPress={() => !isDisabled && onPress(day)}
      disabled={isDisabled}
      style={[styles.slot, style, overrideSlotStyle]}>
      {/* Layer 1: range band (bottom) — left-anchored scaleX grows the fill
          from startDate cell rightward, cell-by-cell staggered. */}
      {bandStyle && (
        <Animated.View
          style={[
            bandStyle,
            {
              backgroundColor: theme.rangeBackground,
              transform: [
                { translateX: bandTranslateX },
                { scaleX: progress },
              ],
            },
            rangeStyle,
          ]}
        />
      )}

      {/* Layer 2: selected circle (middle) */}
      {isSelected && (
        <View
          style={[
            styles.circle,
            {
              backgroundColor: theme.primary,
              borderRadius: theme.dayBorderRadius,
            },
            selectedStyle,
          ]}
        />
      )}

      {/* Layer 3: day number (top) — replaced wholesale by getDayContent when
          provided. Fallback path keeps the default <Text> so textColor / fontSize
          / textStyle / getDayTextStyle still apply. */}
      {customContent !== undefined ? (
        customContent
      ) : (
        <Text
          style={[
            styles.dayText,
            {
              color: textColor,
              fontFamily: theme.fontFamily,
              opacity: isDisabled ? 0.4 : 1,
              fontSize,
            },
            textStyle,
            overrideTextStyle,
          ]}>
          {day.day}
        </Text>
      )}
    </TouchableOpacity>
  )
}

const BAND_HEIGHT = CIRCLE

const styles = StyleSheet.create({
  slot: {
    width: SLOT,
    height: SLOT,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  bandFull: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: (SLOT - BAND_HEIGHT) / 2,
    height: BAND_HEIGHT,
  },
  bandRight: {
    position: 'absolute',
    left: '50%',
    right: 0,
    top: (SLOT - BAND_HEIGHT) / 2,
    height: BAND_HEIGHT,
  },
  bandLeft: {
    position: 'absolute',
    left: 0,
    right: '50%',
    top: (SLOT - BAND_HEIGHT) / 2,
    height: BAND_HEIGHT,
  },
  circle: {
    position: 'absolute',
    width: CIRCLE,
    height: CIRCLE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayText: {
    fontWeight: '500',
  },
})

export default memo(DayCell)
